### ISSUE TITLE
application loading failed that "reactiveAerospikeIndexRefresher bean is timeout"

### ISSUE THREAD

**Issue by boojongmin** [aerospike-community/spring-boot-data-aerospike#44]
I have meet error log when springboot startup by junit 

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'persistenceCacheMemberTable' defined in class path resource [com/play2bit/member/oauthservice/R2dbcConfig$PersistenceCacheConfig.class]: Unsatisfied dependency expressed through method 'persistenceCacheMemberTable' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aerospikeMemberRepository' defined in com.play2bit.member.oauthservice.aerospike.AerospikeMemberRepository defined in @EnableReactiveAerospikeRepositories declared on AerospikeConfig: Cannot resolve reference to bean 'reactiveAerospikeTemplate' while setting bean property 'operations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'reactiveAerospikeTemplate' defined in class path resource [com/play2bit/member/oauthservice/AerospikeConfig.class]: Unsatisfied dependency expressed through method 'reactiveAerospikeTemplate' parameter 5; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactiveAerospikeIndexRefresher' defined in class path resource [com/play2bit/member/oauthservice/AerospikeConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.aerospike.query.cache.ReactorIndexRefresher]: Factory method 'reactorIndexRefresher' threw exception; nested exception is com.aerospike.client.AerospikeException$Timeout: Client timeout: iteration=1 connect=0 socket=1000 total=1000 maxRetries=2 node=BB9020014AC4202 127.0.0.1 3000 inDoubt=true
```

(skip)

```
Caused by: com.aerospike.client.AerospikeException$Timeout: Client timeout: iteration=1 connect=0 socket=1000 total=1000 maxRetries=2 node=BB9020014AC4202 127.0.0.1 3000 inDoubt=true
	at com.aerospike.client.async.NettyCommand.totalTimeout(NettyCommand.java:777)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create
	com.aerospike.client.reactor.AerospikeReactorClient.info(AerospikeReactorClient.java:322)
Error has been observed at the following site(s):
	|_        Mono.create ⇢ at com.aerospike.client.reactor.AerospikeReactorClient.info(AerospikeReactorClient.java:322)
	|_       Mono.flatMap ⇢ at com.aerospike.client.reactor.AerospikeReactorClient.info(AerospikeReactorClient.java:310)
	|_ Mono.doOnSubscribe ⇢ at org.springframework.data.aerospike.query.cache.ReactorIndexRefresher.refreshIndexes(ReactorIndexRefresher.java:47)
	|_      Mono.doOnNext ⇢ at org.springframework.data.aerospike.query.cache.ReactorIndexRefresher.refreshIndexes(ReactorIndexRefresher.java:48)
	|_          Mono.then ⇢ at org.springframework.data.aerospike.query.cache.ReactorIndexRefresher.refreshIndexes(ReactorIndexRefresher.java:52)
Stack trace:
		at com.aerospike.client.async.NettyCommand.totalTimeout(NettyCommand.java:777)
		at com.aerospike.client.async.NettyCommand.timeout(NettyCommand.java:703)
		at com.aerospike.client.async.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:147)
		at com.aerospike.client.async.HashedWheelTimer$HashedWheelTimeout.access$600(HashedWheelTimer.java:123)
		at com.aerospike.client.async.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:187)
		at com.aerospike.client.async.HashedWheelTimer.run(HashedWheelTimer.java:101)
		at com.aerospike.client.async.ScheduleTask.run(ScheduleTask.java:40)
		at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
		at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1703)
		at org.springframework.data.aerospike.config.AbstractReactiveAerospikeDataConfiguration.reactorIndexRefresher(AbstractReactiveAerospikeDataConfiguration.java:52)
```

`"at org.springframework.data.aerospike.config.AbstractReactiveAerospikeDataConfiguration.reactorIndexRefresher(AbstractReactiveAerospikeDataConfiguration.java:52)"`'s source is like this.

![image](https://user-images.githubusercontent.com/9567723/117141750-deb01900-ade9-11eb-8f94-aedb0da77458.png)

how I fix it?

thank you.

ps - my config is..

```
@Configuration(proxyBeanMethods = false)
@EnableReactiveAerospikeRepositories(basePackageClasses = [AerospikeMemberRepository::class])
class AerospikeConfig( @Value("\${aerospike.host}") val host: String ): AbstractReactiveAerospikeDataConfiguration() {
    override fun getHosts() = setOf(Host(host, 3000))
    override fun nameSpace() = "hello"
    override fun eventLoops() = NettyEventLoops(NioEventLoopGroup(1))
}
```

**Comment by tdanylchuk** [comment]
From what I see: you cannot start your application since lib cannot refresh your indices in time, right?

Do you have aerospike running on localhost?
Have you tried to increase aerospike client timeout?

**Comment by boojongmin** [comment]
@tdanylchuk 

thank you comment.

I try this code.

![image](https://user-images.githubusercontent.com/9567723/117152486-0658ae80-adf5-11eb-86e3-59f447e0befa.png)

error message is same...

below capture is `com.aerospike.client.async.NettyCommand.execute(Cluster cluster, AsyncCommand command)`

![image](https://user-images.githubusercontent.com/9567723/117152461-fe990a00-adf4-11eb-8272-ff272c87a3ff.png)

throw timeout is after the method call...

**Comment by tdanylchuk** [comment]
I feel like it's somehow related to the general connection to your node localhost:3000 your client just simply cannot connect to it...

As proposition try to connect to some external well-configured aerospike to check whether it will work for you.
Also try to set up a vanilla aerospike client without spring data and query some records directly from your local aerospike.

**Comment by boojongmin** [comment]
@tdanylchuk 

I have running example other source that blow.

```
@ExtendWith(SpringExtension::class)
@Import(ApplicationConfig::class)
class AerospikeTest {
    @Autowired
    lateinit var t1Repository: T1Repository

    @Test
    fun t1() {
        runBlocking {
            val t1 = T1(1L, "a", 1)
            t1Repository.save(t1).awaitSingle()
            val actual = t1Repository.findByV1AndV2("a", 1).awaitFirstOrNull()
            assertThat(actual).isEqualTo(t1)

        }
    }
}

interface T1Repository: ReactiveAerospikeRepository<T1, Long> {
    fun findByV1AndV2(v1: String, v2: Int): Mono<T1>
}

@Document
data class T1(
    @Id
    val id: Long,
    @Indexed(type = STRING, collectionType = DEFAULT)
    val v1: String,
    @Indexed(type = NUMERIC, collectionType = DEFAULT)
    val v2: Int
)

@Configuration(proxyBeanMethods = false)
@EnableReactiveAerospikeRepositories(basePackageClasses = [T1Repository::class])
class ApplicationConfig : AbstractReactiveAerospikeDataConfiguration() {
    override fun getHosts(): MutableCollection<Host> {
        return mutableSetOf(Host("localhost", 3000))
    }

    override fun nameSpace() = "hello"

    override fun getClientPolicy(): ClientPolicy {
        return super.getClientPolicy().apply {
            failIfNotConnected = true
            timeout = 2000
        }
    }

    override fun eventLoops() = NioEventLoops()
}
```

I try find invalid coding in @Document class and  @Indexed field 

thank you

**Comment by tdanylchuk** [comment]
Not really sure I'm following, so you are saying that it is working with the above example, right?

also, you may try https://github.com/Playtika/testcontainers-spring-boot/ for aerospike func test in case if it reproducible in test, please make the minimum viable project so i can check locally.

**Comment by boojongmin** [comment]
@tdanylchuk 

yes, example is test passed. and local aerospike has data.

![image](https://user-images.githubusercontent.com/9567723/117158443-62720180-adfa-11eb-825e-7df67ae5b97c.png)

**Comment by boojongmin** [comment]
@tdanylchuk 

https://github.com/Playtika/testcontainers-spring-boot/ <- thank you 

I didn't know test container for aerospike. ;;

**Comment by tdanylchuk** [comment]
tip: you can always set up test container by yourself, you just need image + GenericContainer
but this lib will do it for your + bootstrap in spring test

**Comment by boojongmin** [comment]
@tdanylchuk 

ok thank you to your comment are reduce debuging scopes.

I found what is trouble

![image](https://user-images.githubusercontent.com/9567723/117167628-6275ff80-ae02-11eb-97ee-2b6bd789b27e.png)

```
@SpringBootTest(classes = [AerospikeAndR2dbcTest::class])
```

I missed @SpringBootTest annotation.

but I still don't know why run this [code](https://github.com/aerospike-community/spring-boot-data-aerospike/issues/44#issuecomment-832730866)

thank you. and I will put test container my project :)

**Comment by boojongmin** [comment]
Oh. OMZ

sorry this project is `spring-boot-data-aerospike`..

I used by `"com.aerospike:spring-data-aerospike:2.4.2.RELEASE`

so not related this project

but thank you very much.

**Comment by tdanylchuk** [comment]
you are welcome, 
also please close the ticket if you are good with provided info.
